### ISSUE TITLE
Broken link to "key concepts" on PennyLane Documentation page

### ISSUE THREAD

**Issue by pbelevich** [XanaduAI/pennylane#602] opened 2020-04-26 22:03 UTC
#### Issue description

The link "key concepts" in the ["Getting started" section](https://pennylane.readthedocs.io/en/stable/#getting-started) is broken and leads to 404 page.

* *Expected behavior:* Browser opens ["Key Concepts"page](https://pennylane.ai/qml/glossary.html)?

* *Actual behavior:* Browser opens ["Oops!
It looks like that page doesn't exist." page](https://pennylane.ai/404.html)

* *Reproduces how often:* 100%

* *System information:* N/A

**Comment by josh146** [comment] 2020-04-27 03:02
Thanks @pbelevich for letting us know! This has already been fixed in the `master version of the documentation <https://pennylane.readthedocs.io/en/latest/>`_, which follows GitHub master 🙂 Once the next version of PennyLane is released, the 'stable' documentation will also be updated

**Closed by josh146** 2020-04-27 03:02 UTC

**Comment by co9olguy** [comment] 2020-04-27 18:02
@josh146 I wonder if there's anything more we can do to minimize or prevent the mismatches between the `stable` and `latest` versions of docs in the future?

**Comment by josh146** [comment] 2020-04-28 00:33
> @josh146 I wonder if there's anything more we can do to minimize or prevent the mismatches between the stable and latest versions of docs in the future?

Unfortunately not --- this is a case of stable/latest acting as intended. Read the docs pins stable to the most recent release tag, so it is essentially 'immutable'. There are a couple of strategies we can take to mitigate this though:

* Start a practice of having post releases, e.g. `0.8.1.post0`. A post release is typically for minor corrections and updates to the online 'visible' parts of the package, including documentation/READMEs, etc. These are tagged releases on GitHub, but include no code-changes/bug fixes and are *not* uploaded to PyPI. However, post-releases only really work within a week or so from the previous release, before new features and bug fixes are merged in.

* Have a higher frequency of releases, to make sure documentation bug fixes are incorporated into stable as soon as possible.
